- type: web
    name: the-imposter-api
    runtime: python
    plan: free
    buildCommand: pip install --no-cache-dir -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
